### ISSUE TITLE
Revert to using App for main app kind name

### ISSUE THREAD

**Issue by webOS101** [phated/grunt-enyo#2]
Invalid characters in a directory names (e.g. -) can lead to incorrect behavior in apps.  It might be possible to use the regex here:  http://stackoverflow.com/questions/1661197/valid-characters-for-javascript-variable-names to validate but the simpler approach is to revert to App.  I will try to get around to this but I'm filing a bug in case I get distracted like I usually do.

**Comment by phated** [comment]
Have been debating if this was the best course of action.  If I revert back to app, I should be able to submodule bootplate.  Will look into this.

**Comment by webOS101** [comment]
That will probably also get you the other files that seem to be missing from bootplate (e.g. Theme.less)-- Sent from my HP PreOn Nov 24, 2012 2:22 AM, Blaine Bublitz notifications@github.com wrote: Have been debating if this was the best course of action.  If I revert back to app, I should be able to submodule bootplate.  Will look into this.

```
          —
          Reply to this email directly or view it on GitHub.
```

**Comment by phated** [comment]
Uh-oh. The latest version is supposed to have Theme.less

**Comment by webOS101** [comment]
It does.  Pfft.  I did an `npm update enyo` (without the -g) and apparently it made npm mad because it wouldn't update enyo after that and it didn't update the global version.  I was still using 05.

**Comment by phated** [comment]
This module has been deprecated in favor of [generator-enyo](https://www.npmjs.org/package/generator-enyo).

This module was an experiment around using Grunt programmatically wrapped in a CLI.
It basically did what Yeoman has mastered and [generator-enyo](https://www.npmjs.org/package/generator-enyo) should be the standard way to scaffold an enyo project.
