### ISSUE TITLE
Add g11n library

### ISSUE THREAD

**Issue by webOS101** [phated/grunt-enyo#3]

**Comment by phated** [comment]
Is this part of bootplate now?   I believe you can `enyo install:g11n` right now (if it is tagged with a semver tag)

**Comment by webOS101** [comment]
g11n isn't install by default with bootplate (not suggesting it be).  Was merely suggesting it be an optional lib component.  `enyo install:g11n` doesn't seem to work.

**Comment by phated** [comment]
Just checked the g11n library.  It seems that it didn't get (the additional) tag (2.1.0) that the other libraries received that allows it to work with Bower (semver only).

Issue addressing this is at https://enyojs.atlassian.net/browse/ENYO-1407

**Comment by phated** [comment]
This module has been deprecated in favor of [generator-enyo](https://www.npmjs.org/package/generator-enyo).

This module was an experiment around using Grunt programmatically wrapped in a CLI.
It basically did what Yeoman has mastered and [generator-enyo](https://www.npmjs.org/package/generator-enyo) should be the standard way to scaffold an enyo project.
