### ISSUE TITLE
Open browser when debug server is started?

### ISSUE THREAD

**Issue by phated** [phated/grunt-enyo#4]
Just wondering if people would like to have their browser open to localhost:port when debug command is run.  Yeoman does this.

**Comment by webOS101** [comment]
I would make that optional.  It would annoy me to have it do that (beyond the first time, perhaps) as I end up closing the debug and restarting it instead of leaving it open (seems to affect performance on my mac to leave the debug open.  Maybe something like `enyo debug:open`?

**Comment by phated** [comment]
I love `enyo debug:open`!!  I am guessing the debug is causing a performance hit on your computer because it is also watching the filesystem for changes.  I think Grunt uses node's internal FS watch, but I might have read something about it switching to something different in the next release.  I plan to being the Grunt 0.4 conversion of this tool soon.

**Comment by phated** [comment]
This module has been deprecated in favor of [generator-enyo](https://www.npmjs.org/package/generator-enyo).

This module was an experiment around using Grunt programmatically wrapped in a CLI.
It basically did what Yeoman has mastered and [generator-enyo](https://www.npmjs.org/package/generator-enyo) should be the standard way to scaffold an enyo project.
