### ISSUE TITLE
deploy.sh in bootplate/tools is not +x

### ISSUE THREAD

**Issue by webOS101** [phated/grunt-enyo#6]
Minor issue but I'll mention it just the same!

**Comment by phated** [comment]
This module has been deprecated in favor of [generator-enyo](https://www.npmjs.org/package/generator-enyo).

This module was an experiment around using Grunt programmatically wrapped in a CLI.
It basically did what Yeoman has mastered and [generator-enyo](https://www.npmjs.org/package/generator-enyo) should be the standard way to scaffold an enyo project.
