### ISSUE TITLE
enyo build should do a bootplate build if a bootplate project

### ISSUE THREAD

**Issue by webOS101** [phated/grunt-enyo#7]
Seems reasonable to expect that the build process for a bootplate app will run `tools/deploy.sh`.  Further to that is that `index.html` references `build/app.js`, which isn't built by `enyo build` (Related to https://github.com/phated/grunt-enyo/issues/2)

**Comment by phated** [comment]
This module has been deprecated in favor of [generator-enyo](https://www.npmjs.org/package/generator-enyo).

This module was an experiment around using Grunt programmatically wrapped in a CLI.
It basically did what Yeoman has mastered and [generator-enyo](https://www.npmjs.org/package/generator-enyo) should be the standard way to scaffold an enyo project.
